target 'Unrepeatable' do
  use_frameworks!
  pod 'Alamofire', '4.8.2'
  pod 'Tagged', '~> 0.4'
  pod 'PromiseKit', '6.8.4'
  pod 'SkeletonView', '1.5'
  pod 'Kingfisher', '5.5.0'
  pod 'ReactiveSwift', '5.0'
  pod 'ReactiveCocoa', '9.0'
  # Pods for Unrepeatable

  target 'UnrepeatableTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
